HRMSPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import hrms
from hrms import views

app_name = "hrms"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrms.urls', namespace = 'hrms')),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path
from . import views
app_name = 'hrms'


urlpatterns = [
    # Authentication Routes
    # path("",views.index,name="index"),
    path('', views.Index.as_view(), name='index'),
    path('employee_register/', views.Employee_Register_View.as_view(), name='employee_reg'),
    path('employee_login/', views.Employee_Login_View.as_view(), name='employee_login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard/employee/new/', views.New_Employee_View.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/update/',views.Employee_Update.as_view(), name='employee_update'),



      # Admin Routes
    path('admin_login/', views.Admin_Login_View.as_view(), name='admin_login'),
    path('admin_dashboard/', views.Admin_Dashboard.as_view(), name='admin_dashboard'),
    path('admin_dashboard/settings', views.Admin_Setting.as_view(), name='admin_setting'),
    path('admin_logout/', views.Admin_Logout_View.as_view(), name='admin_logout'),
    path("admin_dashboard/report_complaint",views.Complaint_Report.as_view(), name ="report_complaint"),
    path('admin_dashboard/report/', views.Admin_Report.as_view(), name='admin_report'),


     # Manager Routes
    path('manager_login/', views.Manager_Login_View.as_view(), name='manager_login'),
    path('manager_messages/', views.Manager_Message_View.as_view(), name='manager_message'),
    path('manager_dashboard/', views.Manager_Dashboard.as_view(), name='manager_dashboard'),
    path('manager_dashboard/kpd', views.Manager_KPD.as_view(), name='manager_kpd'),
    # path('manager_create_project/', views.Create_Project_View.as_view(), name='create_project'),
    path('manager_assgin_rating/<slug:pk>/', views.Assign_Rating_View.as_view(), name='assign_rating'),
    path('manager_dashboard/project_rating/<int:pk>/view/', views.Rating_View.as_view(), name='rating_view'),
    path('manager/kpi_evaluation/', views.Evaluation_View.as_view(), name='evaluation'),
    path('manager/report/', views.Report_View.as_view(), name='manager_report'),
    path('manager/generate-report/', views.Generate_Report.as_view(), name='gen_report'),
    # path('manager_dashboard/<int:pk>/view/', views.Manager_Dashboard.as_view(), name='manager_dashboard'),
    path('manager_dashboard/settings', views.Manager_Setting.as_view(), name='manager_setting'),
    path('manager_logout/', views.Manager_Logout_View.as_view(), name='manager_logout'),
    path('manager_dashboard/members', views.Manager_Employee_View.as_view(), name='manager_members'),
  



# New Employee Routes
    path('employee_login/', views.Employee_Login_View.as_view(), name='employee_login'),
    path('employee_dashboard/', views.Employee_Dashboard.as_view(), name='employee_dashboard'),
    path('employee_dashboard/<int:pk>/project_detial/', views.Employee_Project_Detail.as_view(), name='project_detail'),
    path('employee_complete_task/', views.Complete_Project.as_view(), name='complete_task'),
    # path('employee_dashboard/project/<int:pk>/detial/', views.Project_Detail_View.as_view(), name='project_detail'),
    path('employee_report/<int:pk>/view/', views.Employee_Report_View.as_view(), name='report_view'),
    path('employee_logout/', views.Employee_Logout_View.as_view(), name='employee_logout'),
    path('employee_complaint/', views.Complaint_View.as_view(), name='employee_complaint'),



#SKPD Routes
    path('employee_dashboard/deliverable_report/<slug:pk>/add/', views.Project_New.as_view(), name='proj_new'),
    path('employee_dashboard/delivable_report/all/', views.Project_All.as_view(), name='proj_all'),
    path('employee_dashboard/delivable_report/<slug:pk>/', views.Project_Detail.as_view(), name='proj_detail'),
    path('employee_dashboard/skpddelivable_report/<slug:pk>/update/', views.Project_Update.as_view(), name='proj_update'),
    path('employee_dashboard/delivable_report/<slug:pk>/delete/', views.Project_Delete.as_view(), name='proj_delete'),
    # path('ajax/load-depts/', views.load_depts, name='ajax_load_depts'), 
    # path('ajax/load-units/', views.load_units, name='ajax_load_units'), 

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    # path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    # path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),








#Bank Routes
    path('dashboard/bank/add/', views.Bank_New.as_view(), name='bank_new'),
    path('dashboard/bank/all/', views.Bank_All.as_view(), name='bank_all'),
    path('dashboard/bank/<slug:pk>/', views.Bank_Detail.as_view(), name='bank_detail'),
    path('dashboard/bank/<slug:pk>/update/', views.Bank_Update.as_view(), name='bank_update'),
    path('dashboard/bank/<slug:pk>/delete/', views.Bank_Delete.as_view(), name='bank_delete'),
    
    
#EmployeeType Routes
    path('dashboard/employeetype/add/', views.EmployeeType_New.as_view(), name='employeetype_new'),
    path('dashboard/employeetype/all/', views.EmployeeType_All.as_view(), name='employeetype_all'),
    path('dashboard/employeetype/<slug:pk>/', views.EmployeeType_Detail.as_view(), name='employeetype_detail'),
    path('dashboard/employeetype/<slug:pk>/update/', views.EmployeeType_Update.as_view(), name='employeetype_update'),
    path('dashboard/employeetype/<slug:pk>/delete/', views.EmployeeType_Delete.as_view(), name='employeetype_delete'),


#Directorate Routes
    path('dashboard/sbu/add/', views.Directorate_New.as_view(), name='sbu_new'),
    path('dashboard/sbu/all/', views.Directorate_All.as_view(), name='sbu_all'),
    path('dashboard/sbu/<slug:pk>/', views.Directorate_Detail.as_view(), name='sbu_detail'),
    path('dashboard/sbu/<slug:pk>/update/', views.Directorate_Update.as_view(), name='sbu_update'),
    path('dashboard/sbu/<slug:pk>/delete/', views.Directorate_Delete.as_view(), name='sbu_delete'),


#Department Routes
    path('dashboard/dept/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/dept/all/', views.Department_All.as_view(), name='dept_all'),
    path('dashboard/dept/<slug:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/dept/<slug:pk>/update/', views.Department_Update.as_view(), name='dept_update'),
    path('dashboard/dept/<slug:pk>/delete/', views.Department_Delete.as_view(), name='dept_delete'),


#Unit Routes
    path('dashboard/unit/add/', views.Unit_New.as_view(), name='unit_new'),
    path('dashboard/unit/all/', views.Unit_All.as_view(), name='unit_all'),
    path('dashboard/unit/<slug:pk>/', views.Unit_Detail.as_view(), name='unit_detail'),
    path('dashboard/unit/<slug:pk>/update/', views.Unit_Update.as_view(), name='unit_update'),
    path('dashboard/unit/<slug:pk>/delete/', views.Unit_Delete.as_view(), name='unit_delete'),
    
    
    
#Station Routes
    path('dashboard/station/add/', views.Station_New.as_view(), name='station_new'),
    path('dashboard/station/all/', views.Station_All.as_view(), name='station_all'),
    path('dashboard/station/<slug:pk>/', views.Station_Detail.as_view(), name='station_detail'),
    path('dashboard/station/<slug:pk>/update/', views.Station_Update.as_view(), name='station_update'),
    path('dashboard/station/<slug:pk>/delete/', views.Station_Delete.as_view(), name='station_delete'),



#Designation Routes
    path('dashboard/design/add/', views.Designation_New.as_view(), name='design_new'),
    path('dashboard/design/all/', views.Designation_All.as_view(), name='design_all'),
    path('dashboard/design/<slug:pk>/', views.Designation_Detail.as_view(), name='design_detail'),
    path('dashboard/design/<slug:pk>/update/', views.Designation_Update.as_view(), name='design_update'),
    path('dashboard/design/<slug:pk>/delete/', views.Designation_Delete.as_view(), name='design_delete'),



#Position Routes
    path('dashboard/position/add/', views.Position_New.as_view(), name='position_new'),
    path('dashboard/position/all/', views.Position_All.as_view(), name='position_all'),
    path('dashboard/position/<slug:pk>/', views.Position_Detail.as_view(), name='position_detail'),
    path('dashboard/position/<slug:pk>/update/', views.Position_Update.as_view(), name='position_update'),
    path('dashboard/position/<slug:pk>/delete/', views.Position_Delete.as_view(), name='position_delete'),
    
    
#KPD Routes
    path('dashboard/kpd/add/', views.KPD_New.as_view(), name='kpd_new'),
    path('dashboard/kpd/all/', views.KPD_All.as_view(), name='kpd_all'),
    path('dashboard/kpd/<slug:pk>/', views.KPD_Detail.as_view(), name='kpd_detail'),
    path('dashboard/kpd/<slug:pk>/update/', views.KPD_Update.as_view(), name='kpd_update'),
    path('dashboard/kpd/<slug:pk>/delete/', views.KPD_Delete.as_view(), name='kpd_delete'),
    

#KPISR Routes
    path('dashboard/kpisr/add/', views.KPISR_New.as_view(), name='kpisr_new'),
    path('dashboard/kpisr/all/', views.KPISR_All.as_view(), name='kpisr_all'),
    path('dashboard/kpisr/<slug:pk>/', views.KPISR_Detail.as_view(), name='kpisr_detail'),
    path('dashboard/kpisr/<slug:pk>/update/', views.KPISR_Update.as_view(), name='kpisr_update'),
    path('dashboard/kpisr/<slug:pk>/delete/', views.KPISR_Delete.as_view(), name='kpisr_delete'),
   
#KPISP Routes
    path('dashboard/kpisp/add/', views.KPISP_New.as_view(), name='kpisp_new'),
    path('dashboard/kpisp/all/', views.KPISP_All.as_view(), name='kpisp_all'),

hrms/views.py
from django.shortcuts import render,redirect, resolve_url,reverse, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Avg,Sum,Count,OuterRef
from django.contrib.auth import get_user_model
from .models  import *
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import FormView, CreateView,View,DetailView,TemplateView,ListView,UpdateView,DeleteView
from .forms import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from braces.views import LoginRequiredMixin,SuperuserRequiredMixin




from hrms.components import *
from hrms.admin_view import *
from hrms.employee_view import *
from hrms.manager_view import *
from hrms.others import *
from hrms.auth import *
from datetime import datetime


# def index(request):
#     return render(request,"hrms/templates/hrms/home/home.html")

# Create your views here.

hrms/templates/hrms/admin/component/sbu/add-sbu.html

<!DOCTYPE html>

{% extends "hrms/admin/component/base.html" %}


{% block body_block %}


      <!-- Beginning of Main Body -->

      <main>
        <h1> Add New SBU Directorate</h1>
        <div class="login-container">
          <p class="title"> SBU Directorate Details </p>
          <div class="separator"></div>
          <p class="welcome-message"> Ensure to fill all fields </p>

          <form method="POST" class="login-form">
              {% csrf_token%}
              {{form.errors}}

              <div class="form-control">
                  <!-- <input type="text" placeholder="Department Name "> -->
                  {{form.sbu_id}}
                  <i class="fas fa-address-book"></i>
              </div>
                  <div class="form-control">
                  <!-- <input type="text" placeholder="Department Name "> -->
                  {{form.sbu_name}}
                  <i class="fas fa-address-book"></i>
              </div>
              <div class="form-control">
                  <!-- <input type="text" placeholder="Department Name "> -->
                  {{form.sbu_email}}
                  <i class="fas fa-address-book"></i>
              </div>
              <div class="form-control">
                  <!-- <input type="text" placeholder="Department Name "> -->
                  {{form.director_of_service}}
              </div>
   

              <div class="button-container">
                <button type="submit" class="button-update"> <a style="text-decoration: none;" href=" {% url "hrms:sbu_all"%} ">Cancel</a> </button>
                  <button type="submit" class="button-update"> Submit SBU Directorate </button>
              </div>
          </form>
      </div>
      
    </main>
     <!-- End of Main Body -->




 {% endblock %}

hrms/templates/hrms/admin/component/sbu/all-sbu.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>

     <!-- Material Icon -->
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">

    <!-- <link rel="stylesheet" href="./assign-rating-table.css"> -->
    <link rel="stylesheet" href=" {% static "admin/managerdashboard.css"%} ">
</head>
<body>
    <div class="container">

      
      <!-- Beginning of Aside or Side Bar -->
      <aside>
        <div class="top">
            <div class="logo">
                
                <h2> Labade <br/> <span class="danger" > Communications </span></h2>
            </div>
            <div class="close" id="close-btn">
                <span class="material-icons-sharp">close </span>
            </div>
        </div>

        <div class="sidebar">
             <a href="{% url 'hrms:admin_dashboard' %}" class="active">
                <span class="material-icons-sharp"> dashboard </span>
                <h3> Dashboard </h3>
             </a>
             <a href="{% url 'hrms:employee_all' %}">
                <span class="material-icons-sharp"> person_outline </span>
                <h3> Employees </h3>
             </a>
      
             <a href="{% url 'hrms:report_complaint' %}">
                <span class="material-icons-sharp"> summarize </span>
                <h3> Employee Complaint </h3>
             </a>
             <a href=" {% url "hrms:admin_setting"%} ">
                <span class="material-icons-sharp"> settings </span>
                <h3> Settings </h3>
             </a>
             <!-- <a href="{% url 'hrms:employment_new' %}">
                <span class="material-icons-sharp"> add </span>
                <h3> Add Employee </h3>
             </a> -->
 
             <a href=" {% url "hrms:admin_logout" %} ">
                <span class="material-icons-sharp"> logout </span>
                <h3> Logout </h3>
             </a>
        </div>
    </aside>
         <!-- End of Aside or Side Bar -->

          <!-- Beginning of Main Body -->

          <main>

            <h1> All SBU/Directorate </h1>

            <div class="button-container">
                <button style="margin: 25px; border-radius: 5px; cursor: pointer;" class="button-update"> <a href="{% url 'hrms:sbu_new' %}" > Add sbu </a> </button>
            </div>

              <div class="insights">

                  <!-- END OF Quick details -->

                  
               

                  <!-- END OF EMPLOYEE ANALYTICS -->

                  
                <!-- BEGINNING OF PROJECT ANALYTICS -->
              

                  <!-- END OF PROJECT ANALYTICS -->
              </div>

              <div class="employee-quick-details-assign-rating">
                <table style="margin: 25px;" >
                    <thead>
                        <tr>
                            <!-- <th style="padding: 15px;"> S/N </th> -->
                            <th style="padding: 15px;"> SBU/Directorate ID </th>
                            <th style="padding: 15px;"> SBU/DirectorateName </th>
                            <th style="padding: 15px;"> Action </th>
                            <th style="padding: 15px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if sbus %}

                        {% for sbu in sbus %}

                        <tr>
                            <!-- <td>  {{sbu.id}} </td> -->
                            <td>  {{sbu.sbu_id}} </td>
                            <td>  {{sbu.sbu_name}} </td>
                            <td> <h3><a href=" {% url "hrms:sbu_detail" pk=sbu.sbu_id %}">View</a></h3> </td>
                        </tr>

                        {% endfor %}

                        {% endif %}

                    </tbody>
                </table>
            </div>
          </main>
           <!-- End of Main Body -->
           <div class="button-container">
            <button style="margin: 25px; border-radius: 5px; cursor: pointer; color: blue;" class="button-update"> <a href="{% url 'hrms:admin_dashboard' %}" > Cancel </a> </button>
        </div>
        
    </div>

    <script src=" {% static "admin/admindashboard.js"%} "></script>
</body>
</html>

hrms/templates/hrms/admin/component/sbu/sbu-delete.html
<!DOCTYPE html>

{% extends "hrms/admin/component/comp-base.html" %}

{% block body_block %}



<main>
    <h1> Are you sure? </h1>

    <div class="button-container">
        <button class="button-update"> <a href="{% url 'hrms:sbu_all' %}" > Return </a> </button>
    </div>

    <div class="employee-analytics">
        <form action="" method="post">
            {% csrf_token %}
            <div class="middle">
                <div style="margin: 10px;" class="left">
                    <h2> Are you sure you want to delete the SUB/Directorate {{object}} All of the following related items will be deleted: </h2>
                </div>
            
            </div>
            <input type="submit" value="Confirm">
            <h3 > <a style="color: rgba(255, 0, 0, 0.948);" href=" {% url "hrms:sbu_detail" pk=sbu.sbu_id %}">No, take me back</a> </h3>

        </form>

        
        </div>


</main>
 <!-- End of Main Body -->






{% endblock %}

hrms/templates/hrms/admin/component/sbu/sbu_details.html
<!DOCTYPE html>

{% extends "hrms/admin/component/comp-base.html" %}

{% block body_block %}



<main>
    <h1> Select SBU/DIRECTORATE to Change </h1>

    <div class="button-container">
        <button class="button-update"> <a href="{% url 'hrms:sbu_all' %}" > Return </a> </button>
    </div>

    <div class="insights">
 

                <!-- BEGINNING OF CURRENT PROJECT/TASKS -->
        <div class="employee-analytics">
            <div class="project-name">
                <h2> {{sbu.sbu_id}} </h2>
            </div>
              <div class="middle">
                  <div style="margin: 10px;" class="left">
                      <h1> {{sbu.sbu_name}} </h1>
                  </div>
              
              </div>
              <div class="middle">
                <div style="margin: 10px;" class="left">
                    <h1> {{sbu.sbu_email}} </h1>
                </div>
            
            </div>
            <div class="middle">
                <div style="margin: 10px;" class="left">
                    <h1> {{sbu.director_of_service}} </h1>
                </div>
            
            </div>
       
              <h3 style="float: right; "> <a style="color: red;" href=" {% url "hrms:sbu_delete" pk=sbu.sbu_id %}">Delete</a> </h3>
              <h3 > <a style="color: blue;" href=" {% url "hrms:sbu_update" pk=sbu.sbu_id %}">Update</a> </h3>
            </div>
    






          <!-- END OF CURRENT PROJECT/TASKS - -->
     

         <!-- END OF CURRENT PROJECT/TASKS - -->
        
    </div>
</main>
 <!-- End of Main Body -->






{% endblock %}